baseURL = "http://example.org/"
languageCode = "fa"
title = "یاvar"
theme= "mini"

googleAnalytics = "G-BYW2J0N60J"

[taxonomies]
    tag = "tags"

[params]
    description = " وبلاگی برای جاوااسکریپت و نود ‌جی‌اس"
    bio = " وبلاگی برای جاوااسکریپت و نود ‌جی‌اس"
    copyright = "مطالب با اشاره به یاvar به عنوان منبع قابل انتشارن."
    home = "خانه"
    tags = "برچسب‌ها"
    about = "درباره یاvar"
    olderPosts = "پست‌های قدیمی‌تر"
    newerPosts = "پست‌های جدیدتر"
    title404 = "۴۰۴ - صفحه پیدا نشد"
    subtitle404 = "چیزی که دنبالش می‌گردید به نظر نمیاد وجود داشته باشه."

    enableGoogleAnalytics = true
    enableComments = true

[markup]
    [markup.highlight]
        style = "github"