baseURL = "http://yavarjs.ir/"
languageCode = "fa"
DefaultContentLanguage = "fa"
title = "یاvar"
theme = "mini"

enableRobotsTXT = true

googleAnalytics = "G-TB5X9PJPXB"

[taxonomies]
    tag = "tags"

[languages]
    [languages.fa]
        languageName = "فارسی"
        weight = "1"
        languageDirection = "rtl"

[params]
    description = " وبلاگی برای جاوااسکریپت و نود ‌جی‌اس"
    bio = " وبلاگی برای جاوااسکریپت و نود ‌جی‌اس"
    copyright = "مطالب با اشاره به یاvar به عنوان منبع قابل انتشارن."
    home = "خانه"
    tags = "برچسب‌ها"
    about = "درباره یاvar"
    olderPosts = "پست‌های قدیمی‌تر"
    newerPosts = "پست‌های جدیدتر"
    title404 = "۴۰۴ - صفحه پیدا نشد"
    subtitle404 = "چیزی که دنبالش می‌گردید به نظر نمیاد وجود داشته باشه."

    showToc = true

    customCSS = ["css/custom.css"]

    enableGoogleAnalytics = true
    enableComments = true

[markup]
    [markup.highlight]
        style = "github"