baseURL = "http://example.org/"
languageCode = "fa"
title = "یاvar"
theme= "mini"

[params]
    description = " وبلاگی برای جاوااسکریپت و نود ‌جی‌اس"
    bio = " وبلاگی برای جاوااسکریپت و نود ‌جی‌اس"
    copyright = "مطالب با اشاره به یاvar به عنوان منبع قابل انتشارن."
    home = "خانه"
    archive = "آرشیو"
    tags = "دسته‌بندی‌ها"
    about = "درباره یاvar"
    olderPosts = "پست‌های قدیمی‌تر"
    newerPosts = "پست‌های جدیدتر"
    title404 = "۴۰۴ - صفحه پیدا نشد"
    subtitle404 = "چیزی که دنبالش می‌گردید به نظر نمیاد وجود داشته باشه."